default: &default
  adapter: postgresql

development:
  <<: *default
  database: locali_development

test:
  <<: *default
  database: locali_test

production:
  <<: *default
  database: locali_production
